import { CreateMLCEngine, InitProgressReport, MLCEngine } from '@mlc-ai/web-llm';
import { portfolioAnswer, portfolioFacts } from './portfolio-knowledge';

const MODEL_ID = 'Qwen2.5-0.5B-Instruct-q4f16_1-MLC';

export type PortfolioStreamEvent = {
  event: 'scope' | 'retrieval' | 'model-loading' | 'token' | 'grounding' | 'complete';
  data: string;
};

export type LocalPortfolioAnswer = {
  answer: string;
  mode: 'verified-response' | 'portfolio';
  notice?: string;
  sources: string[];
};

let enginePromise: Promise<MLCEngine> | null = null;

const scopePattern = /\b(hi|hello|hey|you|your|me|my|who|what|vidit|shah|portfolio|project(s)?|meeraai|meera\s*ai|meera|aarnaai|aarna\s*ai|binance|futures|testnet|cli|robotics|automation|engineering|skill(s)?|technology|python|education|degree|college|gtu|cgpa|experience|career|github|linkedin|contact|email|resume|certificate|course(s)?|interest(s)?|goal(s)?|future|work|built|build|browser|model(s)?|ai|machine learning|computer vision)\b/i;
const outOfScopeReply = "I can only help with my portfolio: my background, projects, engineering work, skills, education, and contact details.";

function relevantContext(question: string) {
  const query = question.toLowerCase();
  const projectFacts = portfolioFacts.projects.filter((project) => {
    const searchable = `${project.title} ${project.description} ${project.tags.join(' ')}`.toLowerCase();
    return searchable.split(/\W+/).some((word) => word.length > 3 && query.includes(word));
  });
  
  const payload: Record<string, unknown> = { 
    identity: portfolioFacts.identity, 
    contact: portfolioFacts.contact 
  };
  
  if (projectFacts.length > 0) payload.projects = projectFacts;
  else if (/project|work|built|build|portfolio/.test(query)) payload.projects = portfolioFacts.projects.map(p => ({ title: p.title, desc: p.description }));
  
  if (/skill|tech|python|stack/.test(query)) payload.skills = portfolioFacts.skills;
  if (/education|degree|college|study|cgpa/.test(query)) payload.education = portfolioFacts.foundation;
  if (/meera|browser|model|tier|inference|local ai/.test(query)) payload.meeraAI = portfolioFacts.meeraAI;

  return JSON.stringify(payload).slice(0, 2000);
}

async function loadModel(emit: (event: PortfolioStreamEvent) => void): Promise<MLCEngine> {
  if (!enginePromise) {
    enginePromise = CreateMLCEngine(MODEL_ID, {
      initProgressCallback: (progress: InitProgressReport) => {
        emit({ event: 'model-loading', data: progress.text });
      }
    });
  }
  return enginePromise;
}

export async function streamPortfolioQuestion(question: string, emit: (event: PortfolioStreamEvent) => void): Promise<LocalPortfolioAnswer> {
  if (!scopePattern.test(question)) {
    emit({ event: 'scope', data: 'Rejected: outside the portfolio-only scope.' });
    return { answer: outOfScopeReply, mode: 'portfolio', sources: ['Portfolio scope'] };
  }

  const verifiedAnswer = portfolioAnswer(question);
  const context = relevantContext(question);
  emit({ event: 'scope', data: 'Accepted: portfolio question.' });
  emit({ event: 'retrieval', data: 'Selected verified portfolio evidence.' });

  try {
    const engine = await loadModel(emit);
    let draft = '';
    
    
    const reply = await engine.chat.completions.create({
      messages: [
        { role: 'system', content: `You are Vidit Shah, a Robotics & AI Engineer. Answer questions about yourself, your skills, and your projects using ONLY the facts below. Speak in the first person ("I", "my", "me"). Be friendly, concise, and professional. Do not introduce any fact that is not in this evidence. Do not mention age, job titles, companies, products, projects, metrics, or future plans unless explicitly present. Evidence: ${context}` },
        { role: 'user', content: question }
      ],
      temperature: 0.1,
      max_tokens: 160,
      stream: true,
    });

    for await (const chunk of reply) {
      const token = chunk.choices[0]?.delta?.content || '';
      draft += token;
      emit({ event: 'token', data: token });
    }

    emit({ event: 'grounding', data: 'Response generated by Web-LLM Llama 3.2.' });
    emit({ event: 'complete', data: 'Verified response ready.' });
    
    const answer = draft.trim();
    if (!answer) throw new Error("Empty draft");
    
    return { answer, mode: 'verified-response', sources: ['Verified portfolio facts', 'Qwen2.5-0.5B (Web-LLM)'] };
  } catch {
    emit({ event: 'grounding', data: 'Local model unavailable. Final response uses verified portfolio evidence.' });
    emit({ event: 'complete', data: 'Verified response ready.' });
    return { answer: verifiedAnswer, mode: 'portfolio', notice: 'The local model could not start on this device. This response uses verified portfolio facts.', sources: ['Verified portfolio facts'] };
  }
}
